-- =====================================================================
-- 03_lnd_ctl_ddl.sql : PCS_LND(수신버퍼) + PCS_CTL(통제) 테이블
--   * SLV/CORE/GOLD 는 dbt 가 생성하므로 여기서 만들지 않는다
-- =====================================================================
SET DEFINE OFF;

-- ---------- PCS_LND : 원천 컬럼 + 적재 메타 ----------
CREATE TABLE PCS_LND.L_SCADA_TRACE (
  EQP_ID       VARCHAR2(20),
  SENSOR_ID    VARCHAR2(20),
  MEAS_TS      TIMESTAMP,
  MEAS_VAL     NUMBER,
  STATUS_CD    VARCHAR2(10),
  LOAD_ID      VARCHAR2(40),       -- DAG run_id
  SRC_SYS      VARCHAR2(20) DEFAULT 'SCADA',
  INGESTED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE INDEX PCS_LND.IX_L_TRACE_ING ON PCS_LND.L_SCADA_TRACE (INGESTED_AT);

CREATE TABLE PCS_LND.L_SCADA_EQP (
  EQP_ID       VARCHAR2(20),
  EQP_NM       VARCHAR2(100),
  LINE_CD      VARCHAR2(20),
  MODEL_CD     VARCHAR2(40),
  USE_YN       CHAR(1),
  LOAD_ID      VARCHAR2(40),
  INGESTED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE PCS_LND.L_SCADA_SENSOR (
  SENSOR_ID    VARCHAR2(20),
  EQP_ID       VARCHAR2(20),
  SENSOR_NM    VARCHAR2(100),
  UNIT         VARCHAR2(20),
  HI_LIMIT     NUMBER,
  LO_LIMIT     NUMBER,
  LOAD_ID      VARCHAR2(40),
  INGESTED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ---------- PCS_CTL : 통제/감사/카탈로그 ----------
CREATE TABLE PCS_CTL.C_JOB_RUN (
  RUN_ID     VARCHAR2(80),
  DAG_ID     VARCHAR2(80),
  TASK_ID    VARCHAR2(80),
  STATE      VARCHAR2(20),
  START_TS   TIMESTAMP,
  END_TS     TIMESTAMP,
  ROW_CNT    NUMBER
);

CREATE TABLE PCS_CTL.C_SOURCE_WATERMARK (
  SRC_SYS         VARCHAR2(20),
  SRC_OBJ         VARCHAR2(40),
  LAST_LOADED_TS  TIMESTAMP,
  CONSTRAINT PK_WM PRIMARY KEY (SRC_SYS, SRC_OBJ)
);

CREATE TABLE PCS_CTL.A_DQ_RESULT (
  RUN_ID     VARCHAR2(80),
  CHECK_NM   VARCHAR2(200),
  PASS_YN    CHAR(1),
  DETAIL     VARCHAR2(1000),
  CHECKED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE PCS_CTL.M_DATA_PRODUCT (
  PRODUCT_NM     VARCHAR2(100),
  OWNER          VARCHAR2(80),
  CONSUMER       VARCHAR2(200),
  REFRESH_CYCLE  VARCHAR2(40),
  GOLD_TABLE     VARCHAR2(120)
);

-- 워터마크 초기값 (전량 1회 적재되도록 과거 시점)
INSERT INTO PCS_CTL.C_SOURCE_WATERMARK (SRC_SYS, SRC_OBJ, LAST_LOADED_TS)
VALUES ('SCADA', 'TRACE_RAW', TIMESTAMP '2000-01-01 00:00:00');

-- 데이터 제품 카탈로그 등록
INSERT INTO PCS_CTL.M_DATA_PRODUCT VALUES
  ('EQP_SENSOR_DAILY_KPI', 'PCS_TECH', 'Workplace/Report', 'DAILY', 'PCS_GOLD.G_WP_EQP_SENSOR_KPI_D');

COMMIT;
EXIT;
