-- =====================================================================
-- 01_users.sql  : 계층 스키마(=유저) 및 권한 생성
-- 참조용 DDL — 외부 Oracle 에 SYSTEM 으로 수동 적용(로컬 컨테이너 제거, → adr/0005)
-- =====================================================================
SET DEFINE OFF;

-- 원천(External Raw) 모사 스키마
CREATE USER SRC_SCADA IDENTIFIED BY src_scada_pw QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO SRC_SCADA;

-- Medallion 계층 스키마
CREATE USER PCS_LND  IDENTIFIED BY pcs_lnd_pw  QUOTA UNLIMITED ON USERS;
CREATE USER PCS_SLV  IDENTIFIED BY pcs_slv_pw  QUOTA UNLIMITED ON USERS;
CREATE USER PCS_CORE IDENTIFIED BY pcs_core_pw QUOTA UNLIMITED ON USERS;
CREATE USER PCS_GOLD IDENTIFIED BY pcs_gold_pw QUOTA UNLIMITED ON USERS;
CREATE USER PCS_CTL  IDENTIFIED BY pcs_ctl_pw  QUOTA UNLIMITED ON USERS;
-- 각 계층 유저는 로그인만 가능하면 됨(객체는 ETL/DBT 유저가 생성/적재)
GRANT CREATE SESSION TO PCS_LND;
GRANT CREATE SESSION TO PCS_SLV;
GRANT CREATE SESSION TO PCS_CORE;
GRANT CREATE SESSION TO PCS_GOLD;
GRANT CREATE SESSION TO PCS_CTL;

-- Airflow 추출 유저: SRC_SCADA 읽기 + PCS_LND/PCS_CTL 적재
CREATE USER PCS_ETL IDENTIFIED BY pcs_etl_pw QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO PCS_ETL;
GRANT SELECT ANY TABLE TO PCS_ETL;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO PCS_ETL;
GRANT CREATE ANY TABLE, ALTER ANY TABLE TO PCS_ETL;
GRANT DROP ANY TABLE TO PCS_ETL;   -- 타 스키마 TRUNCATE 에 필요

-- dbt 실행 유저: PCS_LND 읽기 + PCS_SLV/CORE/GOLD 에 모델 생성/적재
CREATE USER DBT_EXEC IDENTIFIED BY dbt_exec_pw QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO DBT_EXEC;
GRANT SELECT ANY TABLE TO DBT_EXEC;
GRANT CREATE ANY TABLE, DROP ANY TABLE, ALTER ANY TABLE TO DBT_EXEC;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO DBT_EXEC;
GRANT CREATE ANY VIEW, DROP ANY VIEW TO DBT_EXEC;
GRANT CREATE ANY INDEX TO DBT_EXEC;
-- dbt 가 대상 스키마 메타데이터를 조회할 수 있도록
GRANT SELECT ANY DICTIONARY TO DBT_EXEC;

EXIT;
